### ISSUE TITLE
Weird issue with syntax highlighting in multiline comments with markdown

### ISSUE THREAD

**Issue by Arkham** [elixir-editors/vim-elixir#229]
Hi there,

first of all thanks for the amazing work you have done on this addon!

I've noticed a small issue with long multiline comments containing markdown. Here's a gif:

![vim-syntax-elixir](https://cloud.githubusercontent.com/assets/62895/20429356/29a9ba06-ad86-11e6-84b2-2f0b3ecaa560.gif)

As you can see, at some point the syntax highlighting breaks after entering into insert mode. If I exit insert mode and navigate to the top of the file and down again, everything resumes working properly until I enter insert mode again. This is particularly troublesome because it affects the code following the multiline comment as well.

And here's the code that I've used:

```elixir
defmodule Hello do
  @spec count_something(Integer) :: Integer
  @doc """
  All work and no play makes jack a dull boy.

  `hello`

  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.

  `hello`

  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.

  `hello`

  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.

  `hello`

  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  All work and no play makes jack a dull boy.
  """

  def count_something(n) do
    n
  end
end
```

**Comment by Arkham** [comment]
hey there, I would love to try to debug the issue myself :) could you give me a few pointers on where to look and how to write a test for this?

**Comment by jbodah** [comment]
@Arkham Awesome. Take a peek at the other syntax tests (e.g. https://github.com/elixir-lang/vim-elixir/blob/master/spec/syntax/doc_spec.rb#L38)

Are you already familiar with Ruby? The tests are all in Rspec. I believe you'll need gvim or macvim  to run the tests locally

What I would do is finding a failing example (one of the states in your gif) and then play around with the syntax debugging in vim. This is a keybind in my `.vimrc` for debugging syntax under the cursor:

```
" debug syntax highlighting
map <leader>syn :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
      \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
      \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```

That will dump the entire syntax stack. For example:

<img width="783" alt="image" src="https://cloud.githubusercontent.com/assets/6093002/21015660/dd9064fc-bd30-11e6-8a8b-882252a0054c.png">

You will probably see that the text is being recognized as something that it shouldn't be.

[syntax/elixir.vim](syntax/elixir.vim) defines the rules for syntax matching. In general, there are three types of syntax matching functions: `keyword`, `match`, and `region`. You can look at the help docs in vim for more info on each (e.g. `:h syn-keyword`). Those functions take text and match them to syntax groups (labels?). At the bottom of that file you can see that those groups are mapped to highlight groups (with `hi`).

That should be enough to get you started I think. Let us know if you get stuck

**Comment by Arkham** [comment]
Thank you so much for the info, I'll get back with a PR 🌈

**Comment by Arkham** [comment]
I'm back :)

Apparently the issue is caused by vim considering syntax highlighting only the visible part of the screen plus some extra lines. You can read more about it here: http://vim.wikia.com/wiki/Fix_syntax_highlighting

A simple solution would be to add to your `.vimrc` this autocommand:
```viml
if has("autocmd")
  augroup filetype_elixir
    au!
    autocmd FileType elixir autocmd BufEnter * :syntax sync fromstart
  augroup END
endif
```

**Comment by russmatney** [comment]
Thanks much for this - I was experiencing the same issue, and adding that to my .vimrc appears to have fixed it for now - will come back if it pops up again.
