### ISSUE TITLE
string highlighting bug

### ISSUE THREAD

**Issue by nhooyr** [elixir-editors/vim-elixir#281]
https://asciinema.org/a/8nmxl123pqjo2y4cpwzia3lji

The file in question is https://gist.github.com/d7484770b609d657c1c2e1b94d844bde

1. `nvim web.ex`
2. `?channel`
3. `o`
4. Half the screen becomes highlighted as an elixirString

I noticed that if you remove two lines in the syntax file the bug goes away: https://github.com/elixir-lang/vim-elixir/compare/elixir-lang:9cbb3ee...nhooyr:aab2ecd

I am using neovim and I have not tested on vim so I am not sure if this is a neovim only problem.

**Comment by nhooyr** [comment]
I changed the colorscheme of the video to make it easier to see.

**Comment by hauleth** [comment]
I have the same problem. `:syntax sync from start` is temporary fix after leaving insert mode, but this reappears as soon as entering new line.

**Comment by jbodah** [comment]
Currently investigating indent bugs but I'll switch over to look at syntax once those are taken care of. Thanks for the detailed report

**Comment by jbodah** [comment]
Closing - old issue and cannot repro. Feel free to reopen if this is still a bother

**Comment by kelvinst** [comment]
So, I have this issue happening quite randomly, I cannot identify when does that happen, will try to keep an eye and I will post it here if I find out.
