### ISSUE TITLE
script tag highlight

### ISSUE THREAD

**Issue by jbodah** [elixir-editors/vim-elixir#327]

**Comment by mhinz** [comment]
Example?

**Comment by jbodah** [comment]
```eex
<script>
</script>
```

First gets `hi<javaScript> trans<javaScript> lo<javaScript>`
Second gets `hi<htmlSpecialTagName> trans<htmlSpecialTagName> lo<Statement>`

Hmm this one might not be us. It looks like we're loading a subtype plugin. HTML seems to properly highlight for me though when I just edit a `.html` file

**Comment by mhinz** [comment]
Is this still an issue? I get..

First line: `['javaScript', 'htmlScriptTag', 'htmlTagN', 'htmlSpecialTagName']`
Second line: `['htmlEndTag', 'htmlTagN', 'htmlSpecialTagName']`

**Comment by jbodah** [comment]
Haven't tested if it still happens, but I don't think this should be related to us since we bubble up to the HTML rules. Closing
