### ISSUE TITLE
Elixir expression color in eex files.

### ISSUE THREAD

**Issue by bluz71** [elixir-editors/vim-elixir#343]
Hello vim-elixir team,

I have written my own Vim color scheme and I am trying to make it look nice with *eex* files; not having much success.

Basically, Elixir code in `<%=` / `%>` delimiters appears to be highlighted using the *elixirAlias* highlight group which in turn links to the *Type* highlight group.

In my case *Type* is a bold green; nice for types, less nice for statements; basically I see way too much green in eex files. Noting I want to keep bold green for Alias definitions.

I notice an *eelixirExpression* highlight group already exists, but it only appears to effect the colors of parenthesis; no effect on statements. Is that the intention? Why not the expressions themselves?

Is it the intention to use *elixirAlias*/*Type* colouring for Elixir code in eex files?
To me a new group **eelixirStatement** linking to **Statement** would be natural or maybe reuse *eelixirExpression*.

Apologies if I am doing something wrong and I missed something completely obvious. If so, please inform then close this. Otherwise I guess I am asking for an enhancement, as a Vim theme person, to fine tune the coloring in eex files separate from *elixirAlias*.

I appreciate the time and many thanks.

**Comment by jbodah** [comment]
I honestly don't use eex very often although I have noticed several highlight problems when I have used them. My focus as of late has mostly been on improving the indent speed. I'm open to eex changes that make sense

Looking quickly at the code, have you tried highlight `eelixirDelimiter` or `PreProc`? I believe `<%=` and `%>` should be mapped to that. `echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` should give you the syntax stack for the cursor, and I've used that for debugging and building my own color scheme in the past

**Comment by bluz71** [comment]
Yes, keep your focus on improved indent speed. That is more important than this.

Note, `eelixirDelimiter` correctly denotes the colors of the `<%=` and `%>` tags themselves. I am already setting that color, nothing needs to change in that regard.

This issue relates to the Elixir code within `<%=` and `%>` tags, that code, for the most part appears to be highlighted using the `elixirAlias` highlight group; which seems strange and wrong.

This example screenshot highlights the issue. Notice the amount of bold green in Elixir statement code, `for`, `if`, `link`, `topic_path`:

![eex_example](https://user-images.githubusercontent.com/11382509/27505335-9340b586-58e0-11e7-9948-589472c2c116.png)

As best as I can, that color is the chosen from `elixirAlias` highlight group.

Ideally that code should be highlighted using the same coloring as Elixir code in *.ex* files. That notwithstanding, my preference is for a highlight group be made available to allow us Vim theme folks the ability to specify that color and not change the color of `elixirAlias`. Something like `eelixirStatement` or `eelixirExpression`.

I will try and experiment myself and see if I can provide you an example of what I am after.

Lastly, I do appreciate the work you and the team do with this plugin. It works great especially with alchemist.vim.

Best regards.

**Comment by bluz71** [comment]
Here is the same code converted into standard Elixir:

![ex_example](https://user-images.githubusercontent.com/11382509/27505621-e1751f88-58e7-11e7-91b4-2d06dfdae941.png)

Comparing the above two screenshots you can see the overabundance of green in eex files.

Again, this is not a high priority issue.

**Comment by jbodah** [comment]
Thanks for all the info. Would you mind sharing your colorscheme too?

**Comment by bluz71** [comment]
Hello Josh,

My theme is [moonfly](https://github.com/bluz71/vim-moonfly-colors).
Though I get the same issue with the [vim-one](https://github.com/rakr/vim-one) theme; too much yellow in that case.

I did a bit of digging around.
This is nasty; I can not figure out how to fix this.

The main culprit relates to this line:

```viml
syn include @elixirTop syntax/elixir.vim
```

If I change that to:

```viml
syn include @elixirTop syntax/ruby.vim
```

I get much more pleasing syntax highlighting between the delimiters. Note, I am using the polyglot plugin with all syntax files in a single directory; also polyglot does contain all the latest Elixir syntax files (I diff-checked).

`@elixirTop` and how it does what it does in the `eelixirExpression` line is the problem.

I had a look at *Ruby* / *ERB* to compare with *Elixir* / *EEX* and could not make sense of the Vim files (being a complete VimScript novice myself).

Fundamentally, I think this is now actually a bug; likely in *elixir.vim* when given *eex* snippets. Please forget my enhancement requests above; I think a bug is lurking.

I would classify this as medium priority (not high). I am also surprised more folks haven't noticed this? Is it only me?

Thanks for your time.
