### ISSUE TITLE
Different autoindent behaviors between `else` and `end` inside of blocks

### ISSUE THREAD

**Issue by kylethebaker** [elixir-editors/vim-elixir#370]
This is more of a question rather than an issue, so I apologize in advanced if this isn't the appropriate place for this.

I've noticed the auto-indenting behavior differs for `end` and `else` keywords when inside of a block. When typing `else` inside of an `if` block it will auto-indent to align with the opening `if` as soon as you finish typing the word. With `end` inside of a `do` block you have to press enter and insert a new line in order for the indentation to occur. `rescue` and `catch` also have the same behavior as `end` where a newline is required.

Is this expected behavior? I'm wondering if this is intentional to avoid frustration from certain ambiguities (something like `ending = get_ending()` triggering the indent), or possibly for performance reasons when dealing with nested `do` blocks.

I feel like the two behaviors were the same before I updated (not sure what exact commit I was on), though I can't seem to revert to commit where that is the case, so maybe there is something else going on here.

I prefer to have the indentation occur as soon as the word is finished typing, as my workflow involves using `alt+<key>` in order to exit insert mode and issue a command in the same keystroke (typically a directional command). Currently it requires entering a new line in insert mode to trigger the indent which leaves a superfluous blank line that I need to delete and doesn't allow me to exit insert mode as soon as I'm finished typing `end`.

Understandably everyone has different preferences and expectations, so if this behavior is intentional could someone point me in the direction of where this behavior is defined in the code so I can make the adjustment for myself? I've been learning a little bit about vim plugins and trying to familiarize myself with the the code, but I can't find where this behavior is defined.

# Actual

```ex
def foo() do
    :bar
    end▒▏
```

# Expected

```ex
def foo() do
    :bar
end▒▏
```

**Comment by Toady00** [comment]
What you have shown under expected is exactly the behaviour I've seen with this plugin, until today. I upgrade vim via homebrew from version 8.0.0997 to version 8.0.1100_1 and now this plugin's behaviour has changed to what you are actually seeing.

It will actually autoindent it correctly, but only after hitting enter behind `end`. Previously before updating vim, after typing the `d` it would autoindent. This is extremely annoying and while I don't blame the maintainers for something vim appears to have broken, I hope a fix comes soon.

**Comment by Toady00** [comment]
I just used `brew switch vim 8.0.0997` to switch back to the old version of vim. I also had to switch the version of ruby due to some links. But once I switched vim to the old version, the expected behaviour returned, so I think it's confirmed that something changed in vim that broke this behaviour.

**Comment by kylethebaker** [comment]
Thanks for confirming, I am also on vim 8.0 and recently updated. The behavior being triggered by a vim update would explain why I couldn't pinpoint any recent commits to the indent file that were suspect. According to the arch linux repos I am on vim 8.0.1092-1 and it was last updated on 9/11.

I will poke around the vim repo and see if there is an issue related to this. Vim seems to have several commits daily so it's possible the regression has already been recognized and fixed (one can hope).

**Comment by jbodah** [comment]
I've been away for awhile but will take a peek as soon as I can. For reference, this functionality is driven by the expression here: https://github.com/elixir-editors/vim-elixir/blob/master/indent/elixir.vim#L8. Indentation should be corrected both when `end` is typed or when a newline is typed, so it sounds like a regression or change may have caused the former to stop (although I'm not sure why the `else` case would still work)

**Comment by jbodah** [comment]
Doing a binary search on homebrew revs it seems to be something between `8.0.1050` and `8.0.0997` https://github.com/Homebrew/homebrew-core/commits/master/Formula/vim.rb

**Comment by jbodah** [comment]
Did some more diving on this, it looks like `8.0.1041` introduced the change https://github.com/vim/vim/commit/e2e69e48134cbfdedea7802810932f8592705024. Opened an issue over there
