### ISSUE TITLE
length should not be highlighted as a keyword when used as map key

### ISSUE THREAD

**Issue by jbodah** [elixir-editors/vim-elixir#378]
<img width="175" alt="1__task_spec_exs____repos_modern-pastry_apps_task_master__-_nvim__nvim_" src="https://user-images.githubusercontent.com/6093002/31507815-034c749a-af4a-11e7-9d01-85de6a607698.png">

**Comment by jbodah** [comment]
ditto for `.length`

**Comment by hauleth** [comment]
Should it be highlighted as keyword at all?

**Comment by OvermindDL1** [comment]
No, no it should not, length is not a keyword by any stretch.

**Comment by hauleth** [comment]
Resolved by #431 

cc @jbodah
