### ISSUE TITLE
Use global settings for indentation

### ISSUE THREAD

**Issue by GloverDonovan** [elixir-editors/vim-elixir#382]
As I understand it, vim-elixir is hard-coded to use 2 spaces for indentation (see issue #4 and the commit 9ad99d7). Is there any reason why vim-elixir doesn't follow the `.vimrc` settings?

Is there any workaround for this? Ideally it should use the user-defined spacing by default. If for some reason this isn't possible, why not add a plugin variable to handle it?

**Comment by jbodah** [comment]
Hmm I didn't realize that was the case as all of our indent code depends on the value of shiftwidth. Tagging this as a bug

**Comment by jbodah** [comment]
@GloverDonovan just tested this out and it works with `set shiftwidth=4` from what I can see. What are you using to set your indent?

**Comment by GloverDonovan** [comment]
Hi @jbodah 

My .vimrc has `set shiftwidth=4` in it. I tested `shiftwidth=4` in a minimal version of `.vimrc` and it still doesn't work for me. What am I doing wrong?

Here's the `.testvimrc` (I use [`vim-plug`](https://github.com/junegunn/vim-plug)):

```vim
call plug#begin('~/.vim/plugged')
    Plug 'elixir-editors/vim-elixir'    
call plug#end()

set nocompatible               " Use vim defaults (i.e. ignore vi compatibility)

set autoindent                 " Automatically indent new lines

set tabstop=4                  " Show a tab character as 4 spaces
set softtabstop=0              " Edit soft tabs as if they're regular spaces 
set shiftwidth=4               " Make autoindent appear as 4 spaces

set expandtab                  " When using <Tab>, replace the tab character with 4 spaces
set smarttab                   " Always indent based on column number to align things easier

colorscheme default
```

With `vim test.ex -u .testvimrc` I got the same behavior of 2 spaces for indentation and not 4.

**Comment by hauleth** [comment]
@GloverDonovan some of default ftplugins override default `shiftwidth`:

```
abap.vim:setlocal softtabstop=2 shiftwidth=2
ada.vim:   setlocal shiftwidth=3
ada.vim:" vim: textwidth=78 nowrap tabstop=8 shiftwidth=3 softtabstop=3 noexpandtab
cobol.vim:        let &shiftwidth=b:cobol_shiftwidth
falcon.vim:setlocal softtabstop=4 shiftwidth=4 fileencoding=utf-8
man.vim:setlocal shiftwidth=8
occam.vim:setlocal shiftwidth=2
python.vim:    setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=8
rust.vim:	setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
scala.vim:setlocal shiftwidth=2 softtabstop=2 expandtab
shada.vim:setlocal expandtab tabstop=2 softtabstop=2 shiftwidth=2
vroom.vim:setlocal shiftwidth=2
```

So this isn't something unusual. If you want to break community default of 2 spaces then you can use `:h after-directory`.

**Comment by GloverDonovan** [comment]
@hauleth Thanks for the reply. I actually didn't know about the 2 space meta (did some research and some other languages use it as well).

I'll look into the details behind ftplugin and the other files sourced by vim. I'll also consider using the default of 2 spaces since it seems to be the standard for languages like elixir.

**Comment by GloverDonovan** [comment]
Re-opening the issue since I'm not sure what @jbodah thinks of this. Is it still considered a bug?

**Comment by icelye** [comment]
Yup bug i also don't use 2 tabs for indentation. a community spec should not override user preference. Its been driving me nuts for days having to manually set the shift width on each file. @jbodah couldn't the user preference supersede the community spec, the compiler seams to be just okay with 4 spaces.

**Comment by hauleth** [comment]
@icelye as I said, it is common thing in the Vim ftplugins to set the "community default". And to be honest there is no way to "detect" what is the user preference. If you want to force your own shift width despite community standards then you have 2 options:

- per project configuration via EditorConfig (using plugin of your choice)
- globally setting it by creating file `~/.vim/after/ftplugin/elixir.vim` with content:
  ```viml
  setlocal shiftwidth=4

  let b:undo_plugin = b:undo_plugin . ' | sets sw&'
  ```

Also Elixir by default uses `'expandtab'` which mean that it uses spaces for indentation.
