### ISSUE TITLE
Allow `ib` and `ab` to select the current block

### ISSUE THREAD

**Issue by dylan-chong** [elixir-editors/vim-elixir#389]
vim in Ruby files allows `vim`/`vam` to select the current method

It would be nice to be able to do the same thing in Elixir files.

It would also be nice to be able to use `ib`/`ab` to select the current block (inside any `do` block)

**Comment by hauleth** [comment]
I think it should be left out of this plugin, as this plugin shouldn't (in my opinion) introduce new functionalities, but adjust existing to work with Elixir. In such case I would look for (or create) plugin like `vim-textobj-elixir` (with help of [`vim-textobj-user`](https://github.com/kana/vim-textobj-user)).

**Comment by jbodah** [comment]
Closing, I agree with @hauleth - happy to link to another library in the README but vim-elixir already does a lot and I'd prefer people pick and choose the pieces they want by keeping things modular

**Comment by alexparker** [comment]
Would love to know if you found what you were looking for, and/or what you did for `vib/vab` i'd love that in elixir too @dylan-chong

**Comment by dylan-chong** [comment]
I haven't found anything

**Comment by dylan-chong** [comment]
wow incredible ! thank you
