### ISSUE TITLE
Handle errors in `mix format` when using formatprg

### ISSUE THREAD

**Issue by jbodah** [elixir-editors/vim-elixir#401]
This issue is piggy-backing on #399

With a buffer of the following and a cursor at (1,1):

```
defmodule HelloWorld do
def hello do
:hello
end
end
```

`gq2G` will dump error output from `mix format` into the buffer:

```
mix format failed for file: stdin
** (TokenMissingError) stdin:3: missing terminator: end (for "do" starting at line 2)
    (elixir) lib/code.ex:442: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:293: Mix.Tasks.Format.format_file/3
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
:hello
end
end
```

Could this perhaps be wrapped by a script and be silenced on errors? A script would also give us a place to check for the Elixir version

**Comment by hauleth** [comment]
I have written this:

```sh
#!/bin/sh

set -eo pipefail

in="$(mktemp)"
out="$(mktemp)"
trap "rm '$in' '$out' 2>/dev/null" EXIT
cat - > "$in"

if "$@" < "$in" 2>/dev/null > "$out"; then cat "$out"; else cat "$in"; fi
```

Which silences output of failed command, but this will work only on POSIX enabled machines.

**Comment by RobinClowers** [comment]
I would argue that we shouldn't use `mix format` as a formatprg because it only works correctly on whole files. You can use it on a function, but it will outdent it, because it can't tell it's inside a module.

**Comment by jbodah** [comment]
> I would argue that we shouldn't use mix format as a formatprg because it only works correctly on whole files. You can use it on a function, but it will outdent it, because it can't tell it's inside a module.

I think that's fair. It also won't work on partial code. I don't have experience with other formatprg implementations, but I'd be curious how they handle these issues

**Comment by lpil** [comment]
Came here to report this- mix format is not suitable for use with formatprg as it is only intended to work with complete files, not individual vim text objects.

Setting it as formatprg breaks many useful commands in vim.
