### ISSUE TITLE
Incorrect colors of defexception atoms inside a nested error module.

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#411]
Hello, when I had this kind of situation inside vim, the first atom was not colored like the second one:

```
defmodule Dude do
  defmodule DudeTooDudeError do
    defexception [:not_colored, :colored]
  end
end
```

Hope this helps, expected behaviour would be both to be in the same color.
I am using neovim, plug and this entry to install the plugin:
`Plug 'elixir-lang/vim-elixir', { 'for' : 'elixir' }`

This is the commit the plugin is on(if fixed already, although I just updated): `2016fba`

**Comment by jbodah** [comment]
Thanks for the report - just pushed up a fix
