### ISSUE TITLE
Wrong syntax highlight

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#418]
Got following type not syntax highlighted as an atom:

```
@type t :: %TestSuite{test: (() -> any), status: :pending}
```

The `test:` key is different from status(from ExUnit I suppose)

**Comment by mhinz** [comment]
Hmm, there is no difference for me.

Both, `test:` and `status:` are highlighted as `elixirAtom`, if I put that single line in an .ex file.

What does `:echo synIDattr(synID(line("."), col("."), 1), "name")` report if the cursor is over the key?

**Comment by mhinz** [comment]
Well, I can reproduce it with _that_ code. I'll look into it.
