### ISSUE TITLE
Async elixir format process?

### ISSUE THREAD

**Issue by crunchysoul** [elixir-editors/vim-elixir#420]
Not really an issue, but I'm wondering if this plugin is running async when doing elixir formatting, I can feel freeze when running auto format when saving, if not on async, can we make it works async, thank you

**Comment by mhinz** [comment]
@crunchysoul FWIW, it's an already solved problem: https://github.com/mhinz/vim-mix-format :-)

@jbodah Sorry for my inactivity on this repo. I'll try to do better in the future.

**Comment by jbodah** [comment]
Ah nice, thanks for the correction; I think we should link to your repo in the vim-elixir README

**Comment by mhinz** [comment]
With a recent vim-mix-format? It sounds like https://github.com/mhinz/vim-mix-format/commit/52fca66b9771d00602a66753985de852e3c1ede4 should fix your issue.
