### ISSUE TITLE
Wrong atom highlighting for `defrecord`

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#425]
Heya, defrecord highlights atoms of type :"i_am_an_atom" like a string.

Piece of code:
```
defmodule Q do
  defrecord :queue_bind,
            :"queue.bind",
            Record.extract(:"queue.bind", from_lib: "rabbit_common/include/rabbit_framing.hrl")
end
```

`:echo synIDattr(synID(line("."), col("."), 1), "name")` yields elixirString.

**Comment by mhinz** [comment]
Is there any case where is actually gets highlighted as `elixirAtom`?

**Comment by NJichev** [comment]
Yeah, my bad, just noticed it now, should they be atoms tho?

**Comment by mhinz** [comment]
Hmm, I'm not sure about that. :)

The thing is, you can't just use double quotes to include special characters, but it also allows for interpolation. This is valid syntax:

```elixir
num = 123
:"foo #{num} bar"
```

And currently, using `elixirString` for higlighting everything in between the quotes, it automatically highlights the `#{}` accordingly etc. Opposed to the whole thing having the same color (like GitHub does in the code block above) when we would treat it as `elixirAtom`.

Personally I prefer the the current way, but changing it shouldn't be too hard either.

@jbodah What do you think?

**Comment by jbodah** [comment]
I don't feel very strongly either way - if I had to choose I would probably prefer to see the interpolation as it screams "this is dynamic" although I also understand it's not _really_ a string. I can't think of any functional reasons when this would make a difference, so if it's just a an issue of style I'd lean to keep it as-is. If a good reason to change it crops up later though (e.g. some code relies on `elixirAtom`s) then we can revisit it

**Comment by NJichev** [comment]
I’m closing now, I think both reasons are okay. A solution would be making it configurable, but I’m okay with the way it is so it scream at me that something’s not right.

Sorry for wasting time 😅🙇

**Comment by jbodah** [comment]
> Sorry for wasting time

Not at all, thanks for all the reports; would much rather have these issues talked about and closed than having silence and annoying bugs
