### ISSUE TITLE
Syntax highlighting in .html.eex files

### ISSUE THREAD

**Issue by lpil** [elixir-editors/vim-elixir#427]
Hello!

When opening a file with the extension `.html.eex` I would syntax highlighting for both the HTML elements and the embedded Elixir, however I get neither hightlighted- the text is entirely white.

If I check the filetype with `:set filetype?` it returns `filetype=eelixir`.

If I change the filetype with `:set filetype=html.eelixir` the HTML is correctly highlighted, but the embedded Elixir is not.

Is there a way to make this filetype be automatically detected? I believe this worked previously, though I have not checked it in some months.

Cheers,
Louis

**Comment by mhinz** [comment]
`eelixir` subtypes `html` and it should work.

Maybe you're lazy-loading vim-elixir?

**Comment by lpil** [comment]
You got it in one. Thanks, been confusing me for ages <3
