### ISSUE TITLE
Wrong syntax highlight for defoverridable

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#428]
Hello, again!
init: 1 the init part is not highlighted as an atom, since it's a keyword list it should be the case.

```ex
defmodule Test do
  defmacro __using__(_options) do
    quote do
      def init(args) do
        {:ok, args}
      end
      defoverridable init: 1
    end
  end
end
```

# Expected

Highlighted as an atom.

`:echo synIDattr(synID(line("."), col("."), 1), "name")` over `init` yields `elixirOverridableDeclaration`.

**Comment by jbodah** [comment]
Hmm I'm having trouble reproing this. Are you on the latest version of vim-elixir?

Tested it with neovim 0.2.2 and Macvim 8.0. Test added in c353cdc3872e4fd63b40eb156c0dff2169cd4eab

**Comment by jbodah** [comment]
Test added in 882a16fc36db323f4350bd4389c96db8d414cf53. Would you mind verifying on your end?

**Comment by NJichev** [comment]
Yep, just installed newest version and it works fine :bowing_man:
