### ISSUE TITLE
[feature] Elixir text objects.

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#429]
Heya, I have a *small* feature request, those are taken from vim-ruby.

Provide the following elixir text objects:
  * am - outer method definition - selects text between `def` and matching `end`
  * im - inner method definition - selects only the method body
  * aM - outer module definition - selects everything between/including `defmodule` and matching `end`
  * iM - inner module definition - selects everything between `defmodule` and `end`

Here's their documentation in [vim-ruby](https://github.com/vim-ruby/vim-ruby/blob/71f5df78a45c5458da793b2c897ff5dcdcd9a819/doc/vim-ruby.txt#L42)

This will be especially helpful when using vim's motions, e.g:
  * I want to delete everything inside a method - dim
  * I want to copy the whole module - yaM

Something I forgot: the method objects should probably work with private functions and macros(or provide others for macros)

**Comment by NJichev** [comment]
I will close if the stance is the same as in #288 :)

**Comment by jbodah** [comment]
I'm not opposed to this anymore. Related: https://github.com/vim-ruby/vim-ruby/blob/f19516e9e1c183dbf0add52dffb68bca8e61def6/ftplugin/ruby.vim#L188-L191

**Comment by NJichev** [comment]
It seems this will depend on #430 looking at the vimscript code in vim-ruby if you decide to go for the same approach.

**Comment by NJichev** [comment]
Sure, I will look into other options :)
