### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by bbtdev** [elixir-editors/vim-elixir#440]
** Video **
![seg](https://user-images.githubusercontent.com/30316258/43546828-42752f52-95e2-11e8-8d89-6c5748b1de0a.gif)

**Behaviour**
crashes neovim when I open *.exs/ex (elixir) files that have multiple commented lines

**Steps**
1. open *.exs file with multiple commented lines
2. move the cursos so the commneted lines are shown
3. it should crash

** vimrc **

Im only running dein as a plugin manager and polygot, no extra settings/plugins

```
set runtimepath+=/Users/bogdan/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('/Users/bogdan/.cache/dein')
  call dein#begin('/Users/bogdan/.cache/dein')
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

   call dein#add('elixir-editors/vim-elixir')

endif

if dein#check_install()
  call dein#install()
endif
```

**Logs**
https://gist.githubusercontent.com/bbtdev/0b59954f267438e02987ab43d9f5ee3b/raw/0d1e4643b0cc55adcd5c56b5999749e5e05ba28c/gistfile1.txt

**Comment by jbodah** [comment]
Hmm this is a first

Does this still happen without your plugin manager (https://github.com/elixir-editors/vim-elixir/blob/master/manual_install.sh has install steps for vim)?

Are you able to post the file you are editing?

It seems pretty weird that a plugin would be able to segfault nvim so it may be more appropriate to wrangle that team into the conversation

**Comment by mhinz** [comment]
If it crashes, it's a Neovim bug. Please report it at [neovim/neovim](https://github.com/neovim/neovim/issues) and [add a backtrace](https://github.com/neovim/neovim/wiki/Development-tips#backtrace-linux).

**Comment by bbtdev** [comment]
@mhinz @jbodah 
Sorry, it seems there is an issue open on neovim.
https://github.com/neovim/neovim/issues/8607
