### ISSUE TITLE
Cursor flash at the end of lines when typing anything

### ISSUE THREAD

**Issue by lexuanlocqst** [elixir-editors/vim-elixir#447]
Whenever I type any characters, there is cursor flashing at the end of the line. It's really annoying. Does anyone have the same issue?
Here is the example: https://www.youtube.com/watch?v=LT3yGiXONYk

Thank you for your consideration.

**Comment by jbodah** [comment]
Is this issue because of vim-elixir? It shouldn't be as the vim-elixir code should only be activating on .ex, .exs, and .eex files. Does the issue persist if you remove vim-elixir from your bundle or comment it out?

**Comment by lexuanlocqst** [comment]
I'm sorry. I have tried to commit vim-elixir out and then I saw the issue has gone. But actually, it wasn't. Maybe because of my VimRC configurations. I still cannot find out. But I will close this issue. Thanks for your response.

**Comment by jbodah** [comment]
@lexuanlocqst I would recommend doing a binary search on your vimrc; that's worked for me in the past. Comment out half of it to determine which half it's in, then repeat on just the problem half until you narrow it down

**Comment by lexuanlocqst** [comment]
Thank you for your advice. I will try it.
