### ISSUE TITLE
How to only use syntax highlighting?

### ISSUE THREAD

**Issue by raman162** [elixir-editors/vim-elixir#450]
I am only interested in using the elixir syntax highlighting. Is there any way to disable all the other features that were added?

**Comment by jbodah** [comment]
There are buffer variables that can be set for most of the features (e.g. `b:did_indent` [src](https://github.com/elixir-editors/vim-elixir/blob/master/indent/elixir.vim#L1)) which can be set. If you are fine with just disabling indentation then you can set `filtetype plugin indent off` in your `after/elixir.vim` (`:h after-diretory`)

There might be some other options if neither of these work for you

**Comment by raman162** [comment]
thanks very much for the help!
