### ISSUE TITLE
Broken highlighting in heredocs

### ISSUE THREAD

**Issue by fuelen** [elixir-editors/vim-elixir#469]
this file
https://github.com/absinthe-graphql/absinthe_phoenix/blob/master/lib/absinthe/phoenix/controller.ex

![deepin_ - _20190125141153](https://user-images.githubusercontent.com/588762/51745367-3dcf4100-20ab-11e9-8134-5f323611f48d.png)

**Comment by liskin** [comment]
I wanted to get familiar with the codebase so I tackled this one: https://github.com/elixir-editors/vim-elixir/pull/489
