### ISSUE TITLE
.ex files are opened as euphoria3 (again)

### ISSUE THREAD

**Issue by jamesvl** [elixir-editors/vim-elixir#475]
### Summary

`.ex` files are being set to euphoria3 file types instead of Elixir.

### Source of Error
It seems [this commit](https://github.com/elixir-editors/vim-elixir/commit/653cc4d24183558833ee9942cf14731b740d5a55) changed the file type settings so that `.ex` file types are set with `setfiletype` instead of `set filetype=...`. This causes them to no longer recognized as Elixir files (they're seen as euphoria3 files, as mentioned previously in issue #121.)

File type settings were working fine for me prior to the commit linked above.

### Background

From the commit message: 
> Note that the Vim runtime ships with a filetype match for *.ex (for Euphoria), but our plugin-based filetype detection still gets the last say.

Maybe the above isn't working right for Neovim? But the vim help page seems to say `setfiletype` specifically won't work for this:

>   If you want to detect your file after the default file type checks:
>  This works like A above, but instead of setting 'filetype' unconditionally
>   use ":setfiletype".  This will only set 'filetype' if no file type was
>   detected yet.

(note the last sentence; I admit I may be missing information needed to know how plugin-based filetype detection should override this)

### My Setup

This is in Neovim 0.3.3 on Linux, using Pathogen to install this plugin; my init.vim has the `syntax on` line after `pathogen#infect()`.

### My (temporary) Workaround

Per the vim manual, put a file named `ex.vim` into a directory named `/ftdetect` in your vim config directory (which depends on vim / neovim). Place the following line in that file:

`au BufRead,BufNewFile *.ex,*.exs set filetype=elixir`

(This could also be place in your .vimrc / init.vim file.)

**Comment by jbodah** [comment]
Thanks; will revert #473 for now and will see if we can get some test coverage on this. fyi @jparise

**Comment by jparise** [comment]
Thanks! I tested this locally, but there’s obviously still a case where the standard runtime scripts prevale. Sticking with the current approach is the right call.

**Comment by jbodah** [comment]
@jparise What is your local setup? I'm running nvim as well on my home machine and noticed it there

**Comment by jparise** [comment]
Vim 8.1 using vim-plug.

**Comment by mhinz** [comment]
The whole purpose of `setfiletype` is to avoid setting a filetype multiple times during a single event (and all its nested events).

Since `filetype.vim` is sourced very early (triggered by the vimrc or plugin manager using `filetype on`), `setfiletype euphoria3` is done long before `ftdetect/elixir.vim` is read. When the latter than tries `setfiletype elixir`, the filetype won't change. Thus using `set filetype=elixir` is correct.
