### ISSUE TITLE
 something wrong editing the elixir code with spacevim

### ISSUE THREAD

**Issue by CellPhoneYeah** [elixir-editors/vim-elixir#482]
# Actual
ubuntu18.4, I want to edit the elixir code with spacevim, so I modified the configuration according to the official tutorial, but there was a problem when editing, although I reinstallation ubuntu system and spacevim many times

![QQ图片20190310171027](https://user-images.githubusercontent.com/19988436/54083060-ca7f4700-4359-11e9-9de6-bf853d759859.png)

**Comment by mhinz** [comment]
The exceptions happens in one of the plugins provided by SpaceVim and has nothing to do with vim-elixir. Please create an issue with SpaceVim instead.

CC @wsdjeg
