### ISSUE TITLE
leex not highlighting

### ISSUE THREAD

**Issue by aleksbond** [elixir-editors/vim-elixir#488]
I have started using LiveView and I can't seem to get full-on highlighting for leex files.  I pulled down and updated `vim-elixir` locally(today), so the `.leex` extension is getting caught in the `ftdetect`.  This is what I get locally, all my other elixir files are looking good.

![Screen Shot 2019-03-26 at 2 47 58 PM](https://user-images.githubusercontent.com/863592/55029297-c305a200-4fd7-11e9-9b74-ba7993b5cf63.png)

Thanks for having a look, please let me know if you need more details.

**Comment by jbodah** [comment]
Should be fixed by #490
