### ISSUE TITLE
Posibility to diable Dialyxir

### ISSUE THREAD

**Issue by sonic182** [elixir-editors/vim-elixir#494]
Can be disabled Dialyxir usage? It makes my computer sound a lot when I'm working on a project with many dependencies.

Would be nice to have the possibility of toggle it.

If there is already any possibility would be nice to have it documented.

**Comment by blisscs** [comment]
hi @sonic182,

Are you using it with [ale](https://github.com/w0rp/ale)

If yes this is the way I disable dailyzer -
```vim
Test g:ale_elixir_elixir_ls_config = { 
\   'elixirLS': {
\     'dialyzerEnabled': v:false,
\   },  
\}
```

**Comment by sonic182** [comment]
@blisscs thanks!
