### ISSUE TITLE
Wrong highlighting for atom with an `@` in it.

### ISSUE THREAD

**Issue by NJichev** [elixir-editors/vim-elixir#500]
Hi folks!
# Problem:

Wrong syntax highlight for an atom in this case:

```ex
defmodule Test do
  def foo do
    :foo@localhost
  end
end
```
The `@localhost` part gets highlighted as a module attribute.

### Some debug information:
`:echo synIDattr(synID(line("."), col("."), 1), "name")` over each character after and the `@` reports `elixirVariable`.

Otherwise the `:foo` part reports `elixirAtom`

# Expected

The whole atom is highlighted the same.

I know I've opened similar issues, but those were more related to atoms with strings quotes, so I think this one is different :)

If you point out what syntax regex to fix I might give it a go for a first time contribution, but vimscript is scary :roll_eyes: 
Cheers, Nikola!

**Comment by jbodah** [comment]
> vimscript is scary

Fact 😄 

The syntax rules are all defined in https://github.com/elixir-editors/vim-elixir/blob/master/syntax/elixir.vim. My guess would be that it is these match rules that are causing the issue: https://github.com/elixir-editors/vim-elixir/blob/master/syntax/elixir.vim#L44-L46

The regexs tend to be a bit terrifying, but you can generally black-box test them and just read up on the pieces you need to in `:h`

You can verify with a test. For example, this test will jump to the `do` then expect it to be an `elixirAtom`

https://github.com/elixir-editors/vim-elixir/blob/46a68476fc7b4f454c829d83d21997b82ac66f76/spec/syntax/atom_spec.rb#L45-L49

I also tend to use the following command frequently which dumps the syntax of the word under your cursor:

```
map <leader>syn :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
      \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
      \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```

Let me know if that's enough info for you or if you get stuck anywhere
