### ISSUE TITLE
Please do not re-indent the content of multiline strings/heredocs

### ISSUE THREAD

**Issue by vais** [elixir-editors/vim-elixir#505]
It could be argued that the content of multiline strings/heredocs shall not be altered when indenting. At least that's how indentation works in both Ruby and JavaScript Vim plugins. Vim-elixir currently re-indents the contents:

# Before indenting:

```ex
defp sql do
  """
  SELECT *
    FROM table
   WHERE column = 123
     AND another_column = 456
  """
end
```

# Actual (after indenting)

```ex
defp sql do
  """
  SELECT *
  FROM table
  WHERE column = 123
  AND another_column = 456
  """
end
```

# Expected (content inside multiline string shall remain the same before and after indenting)

```ex
defp sql do
  """
  SELECT *
    FROM table
   WHERE column = 123
     AND another_column = 456
  """
end
```

**Comment by jbodah** [comment]
Related: https://github.com/elixir-editors/vim-elixir/issues/346

**Comment by jbodah** [comment]
One idea for how we could implement this: check if the beginning of the line is a string; if it is, don't indent the line
