### ISSUE TITLE
Make examples anything but red

### ISSUE THREAD

**Issue by v0idpwn** [elixir-editors/vim-elixir#507]
Examples should use a more neutral color, like comments themselves. I don't know if this is a bug.

**Comment by jbodah** [comment]
I don't know what your referring to. Could you post a screenshot of what you're referring to?

**Comment by v0idpwn** [comment]
![2019-08-30-211521_242x214_scrot](https://user-images.githubusercontent.com/14948182/64056655-4e78f580-cb6b-11e9-85a5-eacf78ae9f1f.png)

When you use "iex>" on a docstring it becomes red.

**Comment by v0idpwn** [comment]
I don't know, I never had issues with this theme (gotham), but this syntax highliter makes it weird :~

**Comment by w-sanches** [comment]
@v0idpwn There's not much we can do from vim-elixir side as we only define what regions of code mean, but not their colours. Changing the meaning of this region's name will probably break other things and we would be in an infinite loop where solving one issue create others.
If you want a different colour for this specific region I suggest you ask in your favourite theme's repo for them to change the colour of `elixirDocTest` so it does not match the colour of other regions.

**Comment by v0idpwn** [comment]
Well, Guess I'll have to fork my colorscheme then. Sorry for bothering :)
