### ISSUE TITLE
eb06df6 breaks highlighting

### ISSUE THREAD

**Issue by nifoc** [elixir-editors/vim-elixir#510]
After applying eb06df6, syntax highlighting appears to be mostly broken for me.

Example from `mix.exs`:

<img width="465" alt="Bildschirmfoto 2019-09-03 um 20 17 07" src="https://user-images.githubusercontent.com/222412/64198080-de7ab000-ce87-11e9-857a-f81b0e94a9f8.png">

I'm using the latest Neovim commit (`NVIM v0.4.0-1944-g38806f23e`).

Please let me know if you need more information.

Tagging @w-sanches, since he authored the commit.

**Comment by jbodah** [comment]
Thanks for the report - verified that some of the tests had regressions. Reverted for now

**Comment by w-sanches** [comment]
It looks like supporting accentuation, e.g., `:olá`, like elixir does is a little bit more complicated and I overlooked something. I will create a new PR which correctly handles this and add tests ASAP.
