### ISSUE TITLE
Raise should be highlited

### ISSUE THREAD

**Issue by Sgiath** [elixir-editors/vim-elixir#519]
Raise is not technically keyword but is used as one and other syntax-highlighters highlight it.

GitHub highlighter in action
```ex
raise "oops"
```

**Comment by jbodah** [comment]
Seems reasonable to me. The syntax lives in https://github.com/elixir-editors/vim-elixir/blob/master/syntax/elixir.vim if anyone would like to take a shot at updating the regex

Example specs: https://github.com/elixir-editors/vim-elixir/blob/master/spec/syntax/keyword_spec.rb

**Comment by Sgiath** [comment]
This is my first time editing Vim plugin and working with VimL, but it seems pretty straightforward, so I added the MR.
