### ISSUE TITLE
Docs needed: installation

### ISSUE THREAD

**Issue by everettvody** [elixir-editors/vim-elixir#525]
The installation docs need some love.  

I know this is probably old-hat simple stuff for people who already know vim packages, but I followed the instructions given, then I tried editing an Elixir file and.... NOTHING HAPPENED.  No syntax highlighting. Nothing.

The instructions need to get a new user over that line.  "This project has too many examples and its documentation is too thorough" said no developer in the history of development ever.  This looks like an awesome plugin that received a lot of time and attention.  It'd be great if the docs helped others take advantage of that hard work.

**Comment by jbodah** [comment]
>  I followed the instructions given

Could you share what you tried? What environment are you running in? Are you using a package manager like any of the ones listed in the install docs?

I'm more than happy to help or accept PRs to the docs

**Comment by everettvody** [comment]
Steps I took (on Mac):
I renamed my `.vim` directory just to make sure I was getting a fresh start.

1. `git clone git@github.com:elixir-editors/vim-elixir.git`
2. `cd vim-elixir/`
3. `bash manual_install.sh`  (I verified that the `.vim` directory was created and populated)
4. `cd path/to/elixir/project/`
5. `vi mix.exs`

And nothing happened.  Did I miss something?

**Comment by jbodah** [comment]
Could you please confirm that `vi` links to vim and not to vi? Maybe `:echo $VIMRUNTIME` from vim

Could you send me the directory structure that `manual_install.sh` made?

Could you open your `mix.exs` file and tell me the output of `:set ft?`?

**Comment by everettvody** [comment]
On my system, `vi` is an alias for `vim`:
```
❯ vi --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 29 2020 00:47:39)
```
(I did try both `vi` and `vim` in my tests -- same results)

```
❯ ls -Gal ~/.vim
drwxr-xr-x   8 myuser  staff   256 Apr 17 18:54 .
drwxr-xr-x+ 57 myuser  staff  1824 Apr 17 18:54 ..
drwxr-xr-x   4 myuser  staff   128 Apr 17 18:54 autoload
drwxr-xr-x   5 myuser  staff   160 Apr 17 18:54 compiler
drwxr-xr-x   3 myuser  staff    96 Apr 17 18:54 ftdetect
drwxr-xr-x   4 myuser  staff   128 Apr 17 18:54 ftplugin
drwxr-xr-x   4 myuser  staff   128 Apr 17 18:54 indent
drwxr-xr-x   4 myuser  staff   128 Apr 17 18:54 syntax
```

Output of `:set ft`:
```
filetype=elixir
```

**Comment by jbodah** [comment]
So given the last statement it seems like the plugin should've loaded and properly recognized the file type

If you start typing:

```ex
def hello do
  world
```

Does the indentation kick in on the second line?

If you put your cursor on the `d` of `def` and run `:echo synIDattr(synID(line("."),col("."),1),"name")` what does it return (if anything)?

**Comment by everettvody** [comment]
If I start typing a function... nothing happens (no visible changes or highlighting).

Putting my cursor on the `d` in `def` and running
```
:echo synIDattr(synID(line("."),col("."),1),"name")
```
returns nothing.

**Comment by jbodah** [comment]
For syntax, try running `:syntax on`. Does that enable syntax highlighting for you?

**Comment by jbodah** [comment]
For indent, try running `:filetype plugin indent on`. This might need to be done in your `~/.vimrc`. I didn't think we needed to do this any more but that might have not been true in 8.1

**Comment by everettvody** [comment]
Running `:syntax on` DID enable highlighting!  

`:filetype plugin indent on` didn't seem to do anything... but now when I put my cursor over the `d` in `def` and run `echo synIDattr(synID(line("."),col("."),1),"name")`, I get a message:

```
elixirDefine
```

So it appears that things are there.

So now, the dumb question: **What exactly do I have to add to my `~/.vimrc` file to make this work?  (and that should tell us what instructions might best be added to the README).

**Comment by everettvody** [comment]
Also... is it expected that typing `def` automatically creates an `end`?

**Comment by jbodah** [comment]
> **What exactly do I have to add to my ~/.vimrc file to make this work? (and that should tell us what instructions might best be added to the README).

Your `~/.vimrc` should include the following:

```vim
syntax
filetype plugin indent on
```

> Also... is it expected that typing def automatically creates an end?

No, this should be supported by [tpope/vim-endwise](https://github.com/tpope/vim-endwise) though
