### ISSUE TITLE
Allow folding multiline maps, structs and lists

### ISSUE THREAD

**Issue by dkuku** [elixir-editors/vim-elixir#539]
I wanted to start a discussion about folding lists and maps, and structs
also functions with multiple heads would be cool but i'm not sure this is possible
![image](https://user-images.githubusercontent.com/904179/114243359-53776b00-9984-11eb-9bb8-9975239af7e9.png)

# Actual
its not possible to fold lists - it closes the whole function body
```ex
  def project do
    [
      app: :lvsolitaire,
      version: "0.1.0",
      elixir: "~> 1.5",
      elixirc_paths: elixirc_paths(Mix.env()),
      compilers: [:phoenix, :gettext] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

```

# Expected
I think it would be useful to fold these - my example is short but you can have a list inside a map and this can get long

**Comment by jbodah** [comment]
Lists, maps, etc should be possible. I'm less confident about function heads (in the way you displayed at least - the when block in the first head in particular)

**Comment by dkuku** [comment]
It was just an idea, I looked at the file syntax and this would be hard to do - you can probably fold to the next 'def something_else() do'  but then you may have @spec and @doc inbetween so these should not be folded. Lists and maps are fine
