### ISSUE TITLE
Elixir files are automatically folded upon opening

### ISSUE THREAD

**Issue by sashaafm** [elixir-editors/vim-elixir#540]
Elixir files are being automatically folded upon being opened. I believe this is happening due to this commit: https://github.com/elixir-editors/vim-elixir/commit/5a1811c3c70adeee42d9dc5faae1cba1d57461f9

I deleted the `vim-elixir` plugin and this behaviour went away. This and the fact I had just updated my Vim plugins leads me to believe this latest commit is the reason.

How can this behaviour be disabled? Furthermore, shouldn't the reverse behaviour (no automatic folding) be the default? I found this to be quite surprising and has led me to dig through Vim issues and help sections to fix it (until I thought maybe this plugin was the culprit). 

EDIT:

Running `:verbose set foldmethod` shows this 🙂 can we make it more explicit how to opt out of this behaviour? 
```
foldmethod=syntax
        Last set from ~/.vim/bundle/vim-elixir/syntax/elixir.vim line 13
```

**Comment by jbodah** [comment]
Reverted, thanks
