### ISSUE TITLE
Long strings in an Elixir file slow everything down terribly.

### ISSUE THREAD

**Issue by sharnik** [elixir-editors/vim-elixir#55]
I'm working with such a short Elixir program: https://gist.github.com/sharnik/6727624

The issue is that it takes a few seconds to display the line with the long string when opening the file. Also, any command in insert mode takes an extra few seconds to process.

**Comment by JustMikey** [comment]
What helped me was to set the `set lazyredraw` in my vimrc file, it affects the animation to some point but it's not freezing anymore.
