### ISSUE TITLE
~H sigil syntax highlighting breaks on < and > inside embedded elixir tags

### ISSUE THREAD

**Issue by codeanpeace** [elixir-editors/vim-elixir#566]
Working theory is that the syntax highlighting for Elixir (.ex) files is not looking for the `%` sign to determine a matching closing tag for embedded Elixir opening tags. This means a `>` character would prematurely close the embedded tag while a `<` character would appear to open a tag within a tag. 

# Actual
![image](https://user-images.githubusercontent.com/2991389/211691537-5daeabb7-7108-4ce3-bef1-841ceda8b7f0.png)
![image](https://user-images.githubusercontent.com/2991389/211691486-e2fe86a2-e1e4-42c6-9ed9-523df47ff6ec.png)

# Expected
```ex
<%= if Enum.count(@assets) > 1 do %>
```
```ex
<%= for asset <- @assets do %>
```

**Comment by samanera** [comment]
Couldn't reproduce it @codeanpeace , here's how it looks with my configuration:

<img width="330" alt="image" src="https://github.com/elixir-editors/vim-elixir/assets/141537607/bc8e89c7-3486-4165-afab-7c9af80397bc">

Do you have more details? Perhaps, which version of Vim are you using and which version of `vim-elixir` are you running?

**Comment by samanera** [comment]
Missed the part about the ~H sigil. (The most important one. 😅)
