### ISSUE TITLE
Volunteering as maintainer

### ISSUE THREAD

**Issue by sodapopcan** [elixir-editors/vim-elixir#571]
Hey there,

I'm looking to volunteer as co-maintainer or even to take over as this repo hasn't seen an update in 2 years.  I'd really like to get some things merged in.

Thanks!
Andrew

**Comment by jbodah** [comment]
Thanks for the help! I will get to your other PRs later this week. I'll also figure out who I need to talk to add you as a committer.

**Comment by jbodah** [comment]
Just updating. I've tried reaching out to org owners a few ways with no luck. I'll keep an eye on any PRs you post in the meantime.

**Comment by jbodah** [comment]
@ericmj @josevalim @lexmag @michalmuskala @whatyouhide

Sorry for the wide cast. I've been unable to reach anyone via other methods. Would one of you be able to add @sodapopcan as a maintainer for this repo?

**Comment by josevalim** [comment]
Hi @jbodah, I replied to you on ElixirForum a couple weeks ago. I told you that I gave you admin permission to the repo, so you should be able to add someone. Does that work?

**Comment by jbodah** [comment]
Ah, you're right. I must have missed the notification. All set - thanks!

**Comment by sodapopcan** [comment]
Thanks so much @jbodah!!

**Comment by josevalim** [comment]
Hooray!!!
