### ISSUE TITLE
Request: Add version tag

### ISSUE THREAD

**Issue by sodapopcan** [elixir-editors/vim-elixir#577]
Hey hey,

I'm trying to use [vim-flavor](/kana/vim-flavor) along with [vim-vspec](/kana/vim-vspec) which requires vim plugins to follow semvar.  Would you be opposed to adding a `0.1.0` version tag or the like?

Thank you!

**Comment by sodapopcan** [comment]
Actually, I realize I can just use my fork.  Feel free to close unless you're game to add one.

**Comment by jbodah** [comment]
I don't feel strongly. I can't think of a practical application for semver - everyone will want to be on edge or on latest stable (usually a few days behind edge - if someone breaks, then we'll usually get a ticket). Not opposed to adding a version file for the sake of it however.

**Comment by sodapopcan** [comment]
I actually no longer need this as I've figured out how to develop my plugin without depending on elixir.vim, especially since being granted commit access (thanks again!!) as I'm able to fix some inconsistencies around syntax definitions.
